import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'First NextJS with TypeScript',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          width: "100%",
          background: "slateblue",
          fontSize: "50px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center"
        }}>
          <Link style={{margin: "7px"}} href="/">🏠 Home |</Link>
          <Link style={{margin: "7px"}} href="/posts"> 📋 Posts |</Link>
          <Link style={{margin: "7px"}} href="/articles">📝 Articles</Link>
        </nav>
        {children}</body>
    </html>
  )
}
